# name — это главный заголовок нашего пайплайна.
# Текст ниже будет красиво отображаться крупным шрифтом во вкладке Actions на GitHub.
name: QA Smoke Check

# Блок on указывает условия-триггеры.
# Он отвечает на вопрос: «В какой именно момент робот должен проснуться?»
on:

  # push означает: запускать робота при отправке кода с компьютера на GitHub
  push:
    # branches указывает конкретную ветку. Робот сработает только при пуше в master.
    branches: [ master ]

  # pull_request означает: запускать робота, когда кто-то создаёт запрос на слияние на сайте
  pull_request:
    # Робот проверит код в черновике перед тем, как разрешить влить его в master.
    branches: [ master ]

# Блок jobs — это список крупных задач (работ), которые должен сделать робот.
jobs:

  # smoke-test — это технический идентификатор (ID) нашей конкретной работы.
  # Мы назвали её «дымовой тест» (базовая проверка жизнеспособности).
  smoke-test:

    # runs-on приказывает GitHub выделить нам в своём облаке
    # чистый виртуальный компьютер на базе операционной системы Linux Ubuntu.
    runs-on: ubuntu-latest

    # Блок steps — это пошаговый список мелких команд, 
    # которые робот выполнит на этом сервере Ubuntu строго сверху вниз.
    steps:

    # Символ дефиса «-» означает начало нового шага.
    # uses вызывает готовый официальный скрипт от создателей GitHub.
    # Этот шаг заходит в наш репозиторий, скачивает все файлы на сервер Ubuntu и распаковывает их.
    - uses: actions/checkout@v4

    # name задаёт понятное имя шага для человека (его мы увидим в логах на сайте).
    - name: Show repo structure
      # run запускает реальную консольную команду Linux. 
      # ls -la выведет на экран список всех скачанных файлов проекта (включая скрытые папки).
      run: ls -la

    # Следующий шаг-тест. Проверяет, не забыли ли мы важный файл документации.
    - name: Check README exists
      # test -f README.md — проверяет, существует ли физически этот файл.
      # && echo ... — если файл на месте, робот выведет в логи зелёный текст.
      # || (...) — если файла нет, робот выведет ошибку и завершит работу с кодом exit 1.
      # exit 1 принудительно ломает конвейер и красит весь запуск на GitHub в красный цвет.
      run: test -f README.md && echo "README.md found" || (echo "README.md missing" && exit 1)

    # Точно такой же шаг-тест, но для проверки файла правил игнорирования мусора.
    - name: Check .gitignore exists
      # Робот проверяет, на месте ли .gitignore. Если кто-то случайно удалил его из master,
      # тест немедленно упадет (exit 1) и предупредит нас об этом до того, как код пойдет дальше.
      run: test -f .gitignore && echo ".gitignore found" || (echo "README.md missing" && exit 1)
